
version: '3'

networks: 
  lumen:

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_lumen
    ports: 
      - 7000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mongodb
    networks: 
      - lumen
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_lumen
    volumes:
      - './data-mongodb:/data/db'
    restart: unless-stopped
    tty: true
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: controlepessoas
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    networks: 
      - lumen

  #mysql:
  #  image: mysql:8
  #  command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
  #  container_name: mysql_lumen
  #  restart: unless-stopped
  #  tty: true
  #  ports: 
  #    - "9306:3306"
  #  environment: 
  #    MYSQL_DATABASE: controlepessoas
  #    MYSQL_USER: lumen_db
  #    MYSQL_PASSWORD: 123456789
  #    MYSQL_ROOT_PASSWORD: 123456789
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mysql
  #  networks: 
  #    - lumen
  #  volumes: 
  #    - ./mysql:/var/lib/mysql
  # Obs. Caso usar o mysql crie uma pasta no seu diretório chamada (mysql)

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_lumen
    tty: true
    volumes: 
      - ./src:/var/www/html
    ports: 
      - '9004:9004'
    networks: 
      - lumen

  composer:
    image: composer:latest
    container_name: composer_lumen
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - lumen

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_lumen
    volumes:
      - ./src:/var/www/html
    depends_on: 
      - mongodb
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - lumen

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_lumen
    restart: always
    tty: true
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados-rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    depends_on:
      - php
      - mongodb
    networks: 
      - lumen